name: Build on macOS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  macOS:
    name: Build on macOS
    runs-on: macOS-15
    steps:
    - name: Print Swift version
      run: swift --version
    - name: Checkout
      uses: actions/checkout@master
    - name: Swift build
      run: swift build -c release
